name: Build and publish Docker images

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  push_to_registry:
    name: Build and push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "[7.4][min] Build and push Docker image"
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: 7.4
          target: min
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          push: true
          tags: |
            jopplt/php:7.4-fpm-min

      - name: "[7.4][newrelic] Build and push Docker image"
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: 7.4
          target: newrelic
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          push: true
          tags: |
            jopplt/php:7.4-fpm-newrelic
          build-args: |
            NEW_RELIC_AGENT_VERSION=9.18.1.303

      - name: "[7.4][dev] Build and push Docker image"
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: 7.4
          target: dev
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          push: true
          tags: |
            jopplt/php:7.4-fpm-dev