name: PHP 7.4

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 7.4/**
  release:
    types: [ published ]

jobs:
  push_to_registry:
    strategy:
      matrix:
        image:
          - name: "[7.4][min]"
            target: "min"
            context: 7.4
            tags: |
              jopplt/php:7.4-fpm-min
            build-args: ""
            platforms: linux/amd64,linux/arm64,linux/ppc64le
          - name: "[7.4][newrelic]"
            target: "newrelic"
            context: 7.4
            tags: |
              jopplt/php:7.4-fpm-newrelic
            build-args: |
              NEW_RELIC_AGENT_VERSION=9.18.1.303
            platforms: linux/amd64,linux/arm64,linux/ppc64le
          - name: "[7.4][dev]"
            target: "dev"
            context: 7.4
            tags: |
              jopplt/php:7.4-fpm-dev
            build-args: ""
            platforms: linux/amd64,linux/arm64,linux/ppc64le
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "${{ matrix.image.name }}"
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.image.context }}
          target: ${{ matrix.image.target }}
          platforms: ${{ matrix.image.platforms }}
          push: true
          tags: ${{ matrix.image.tags }}
          build-args: ${{ matrix.image.build-args }}