name: PHP 8.3

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 8.3/**
  release:
    types: [ published ]

jobs:
  push_to_registry:
    strategy:
      matrix:
        image:
          - name: "[8.3][base]"
            target: "base"
            context: 8.3
            tags: |
              jopplt/php:8.3-fpm-base
            build-args: |
              COMPOSER_VERSION=2.7.7
            platforms: linux/amd64,linux/arm64
          - name: "[8.3][dev]"
            target: "dev"
            context: 8.3
            tags: |
              jopplt/php:8.3-fpm-dev
            build-args: |
              COMPOSER_VERSION=2.7.7
            platforms: linux/amd64,linux/arm64
      fail-fast: true
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "${{ matrix.image.name }}"
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.image.context }}
          target: ${{ matrix.image.target }}
          platforms: ${{ matrix.image.platforms }}
          push: true
          tags: ${{ matrix.image.tags }}
          build-args: ${{ matrix.image.build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max